### PR TITLE
v0.6.0

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b4fb83c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b4fb83c77d535a8e34d6ebb9c2aa220dc1da4005 with merge 3957b176f4f0b488961c03b266d13930c2980ce3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x/builds/329235119?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 3957b176f4f0b488961c03b266d13930c2980ce3 to master...

**Pull request merged**
