### PR TITLE
make writes to USARTx.TDR safe

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f3f8064 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f3f80648fc3a122a03230044deed0c83b9ba9654 with merge 66ed69e7e2d6a8610f682c7798b01e700af8341f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x/builds/328257164?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 66ed69e7e2d6a8610f682c7798b01e700af8341f to master...

**Pull request merged**
