### PR TITLE
make write to some I2C registers safe

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4ee7387 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4ee7387bcfb27d91436cb7f00f9205e3536ce0c6 with merge 79d6721f75ae86b30985215cd84b8f5bf8c3e120...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/stm32f30x/builds/328305305?utm_source=github_status&utm_medium=notification)

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x/builds/328305305?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 79d6721f75ae86b30985215cd84b8f5bf8c3e120 to master...

**Pull request merged**
