### PR TITLE
ci: check that the patch can be applied to the SVD file

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f28aedb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f28aedb with merge f28aedb...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x/builds/235332831?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing f28aedb409dfbbbac4400531661b2c03590deb5f to master...

**Pull request merged**
