### PR TITLE
fix resetValue of some GPIO registers

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f5ecbbe has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f5ecbbe98097550e0806a673bbe36b07f89e99b7 with merge d40bda2d43e6fadc909e3b81b0d821785b9573fd...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/stm32f30x/builds/326126152?utm_source=github_status&utm_medium=notification)

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x/builds/326126152?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing d40bda2d43e6fadc909e3b81b0d821785b9573fd to master...

**Pull request merged**
