### PR TITLE
add USART3EN field to RCC.APB1ENR

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0e04b45 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0e04b453029a118d039edc0fa0fccc2b147ba502 with merge 297b58ca475b99a6eb4ea9f61a5b26bdcb5a4c61...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x/builds/327052186?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 297b58ca475b99a6eb4ea9f61a5b26bdcb5a4c61 to master...

**Pull request merged**
