### PR TITLE
fix resetValue of some SPI registers

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 897edb1 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 897edb157bf39310bc23bef7057c286b1da357f5 with merge 6848c612168605ff7ec8d8aa2fd05beaa66e8e18...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/stm32f30x/builds/326188201?utm_source=github_status&utm_medium=notification)

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x/builds/326188201?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 6848c612168605ff7ec8d8aa2fd05beaa66e8e18 to master...

**Pull request merged**
