### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 416356f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 416356f with merge 416356f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f30x/builds/234892745?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 416356f18b7ae89f8f91df70856704d3be156e0a to master...

**Pull request merged**
